// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB3HyCHPF9K-0ttNtkx7Xy-C-7oPVLg6o',
    appId: '1:283492446941:web:cde69f040d1a612f96a134',
    messagingSenderId: '283492446941',
    projectId: 'laravel-final',
    authDomain: 'laravel-final.firebaseapp.com',
    storageBucket: 'laravel-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTRGCX6fHjIryIKPfA5hGg6DdeNLAqMB4',
    appId: '1:283492446941:android:bd442100ebe32f3596a134',
    messagingSenderId: '283492446941',
    projectId: 'laravel-final',
    storageBucket: 'laravel-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq4gp6HagPg0bYj5fM7pblNYMzRdwJuC8',
    appId: '1:283492446941:ios:8e9bedcf227c52c596a134',
    messagingSenderId: '283492446941',
    projectId: 'laravel-final',
    storageBucket: 'laravel-final.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq4gp6HagPg0bYj5fM7pblNYMzRdwJuC8',
    appId: '1:283492446941:ios:8e9bedcf227c52c596a134',
    messagingSenderId: '283492446941',
    projectId: 'laravel-final',
    storageBucket: 'laravel-final.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB3HyCHPF9K-0ttNtkx7Xy-C-7oPVLg6o',
    appId: '1:283492446941:web:c0755490573818c296a134',
    messagingSenderId: '283492446941',
    projectId: 'laravel-final',
    authDomain: 'laravel-final.firebaseapp.com',
    storageBucket: 'laravel-final.appspot.com',
  );
}
